### PR TITLE
Get the property of artifacts

### PR DESCRIPTION
**Pull request by sks**

### CODE REVIEW

**Comment by eyalbe4** [comment]
@sks,
A different approach might be enhancing the existing the *jfrog rt search* command, so that it can also return the properties attached to the artifacts it finds.

**Comment by sks** [comment]
@eyalbe4 : Thanks for the input. 

I have made the changes. Please let me know

**Comment by tru** [comment]
I was just looking for this functionality. Great to see this being working on, hope it can be approved and rolled into the CLI soon

**Comment by eyalbe4** [comment]
Thanks you for this @sks!
Can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your code?

**Comment by sks** [comment]
@eyalbe4 👍 

Done

**Comment by sks** [comment]
I have signed the Agreement, is there a bot or something that update with the status on the PR ?

**Comment by eyalbe4** [comment]
Thank you @sks.
We'll soon review the code.

**Comment by sks** [comment]
Ended up using Docker image that has `jforg cli ` installed

```
FROM golang:alpine as builder

RUN apk update && \
    apk upgrade && \
    apk add git zip && \
    go get github.com/jfrogdev/jfrog-cli-go/jfrog-cli/jfrog

WORKDIR /go/src/github.com/jfrogdev/jfrog-cli-go/jfrog-cli/jfrog

RUN git fetch origin pull/104/head:feature/get_artifact_prop && \
    git checkout feature/get_artifact_prop && \
    go build -o /tmp/jfrog

FROM alpine:latest
RUN apk --no-cache add ca-certificates zip

COPY --from=builder /tmp/jfrog    /bin/jfrog

CMD ["jfrog"]
```

**Comment by eyalbe4** [comment]
Thanks for the contribution @sks and sorry for the late response.

**Comment by eyalbe4** [comment]
@sks,
We renamed the **properties** object in the JSON returned by the *search* command to *props*, to be consistent with the **props** in the File Specs. See [this](https://github.com/JFrogDev/jfrog-cli-go/commit/061344a25fc4d016c152ebea75992488294265da) commit to the *dev* branch.
Thanks again for contributing the code.
```
[
  {
    "path": "generic-local/debug_start.sh",
    "props": {
      "a": "1",
      "debug": "false"
    }
  },
  {
    "path": "generic-local/start.sh"
  },
  {
    "path": "generic-local/agent.jar"
  },
  {
    "path": "generic-local/settings.xml"
  }
]
```

**Pull request merged**
