### PR TITLE
Support AQL Sort and Limit

### PR DESCRIPTION
**Pull request by drorb**
Added support for AQL sort and limit, for example:
```

{
  "files": [
    {
      "aql": {
        "items.find": {
          "repo": "libs-release-local"
        },
        "sort" : {"$desc" : ["name"]},
        "limit" : 5
      },
      "target": "files"
    }
  ]
}
```

### CODE REVIEW

**Comment by kpersohn** [comment]
This looks great; any chance of seeing it merged into a release soon? We're anxious to try it out. 

For reference, this fixes #56.

**Comment by eyalbe4** [comment]
Hi @kpersohn. I agree. We do want to merge this pull request.
We'll soon finish testing this and merge the code.

**Comment by eyalbe4** [comment]
Here's an update:
We're considering an alternative for this implementation, to make the AQL you can define in the File Spec less restrictive. We'll update with more information as our research progresses.

**Comment by jgeorgeson** [comment]
Any timeline for this?

**Comment by eyalbe4** [comment]
Sure @jgeorgeson,
We plan to commit the code to the dev branch next week, so that it can be added to the upcoming release next month.
We'll update this issue with some more details after the commit.

**Comment by jgeorgeson** [comment]
awesome.

**Comment by jgeorgeson** [comment]
My hope for this feature is the ability to have an AQL spec file that lets me delete all the the _N_ youngest builds in a repo whose packaging/layout doesn't support automatic integration build cleanup. Is that something you expect to be able to support?

**Comment by eyalbe4** [comment]
Yes @jgeorgeson,
The File Spec schema will be extended and include three additional properties - *sort-by*, which accepts any of item AQL domain fields, *sort-order* and *limit*.
These properties will also be exposed as command options.

**Comment by eyalbe4** [comment]
@jgeorgeson,
Most of the sort and limit code has been pushed by @DimaNevelev into the *dev* branch.

**Comment by eyalbe4** [comment]
@jgeorgeson and @kpersohn,
Version 1.12.0 adds sort and limit support. We'd appreciate your feedback for it. Since we can use https://github.com/JFrogDev/jfrog-cli-go/issues/56, I think we can closing this pull request.

**Pull request closed without merging**
